---
sudo: false
language: ruby
cache:
  - bundler
# http://rubies.travis-ci.org/
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
before_install:
  - gem install bundler -v 2.0.2
script:
  - bundle exec rake schema:update
  - bundle exec rake
